---
# File: macosx/cluster_install.yml
# Ansible playbook to configure operating system and install Couchbase Server

- hosts: centos
  gather_facts: False
  sudo: True
  roles:
  - bootstrap/centos
  - bootstrap/common
  - couchbase-server/centos
  - couchbase-server/common

- hosts: ubuntu
  gather_facts: False
  sudo: True
  roles:
  - bootstrap/ubuntu
  - bootstrap/common
  - couchbase-server/ubuntu
  - couchbase-server/common
