---
# File: macosx/create_bucket.yml
# Ansible playbook to create a new Couchbase Server bucket

- hosts: cluster_nodes
  gather_facts: False
  sudo: True
  tasks:
  - name: Create cluster grouping
    group_by: key={{ node_role }}

- hosts: primary
  gather_facts: False
  sudo: True
  vars:
    primary_node: "{{hostvars[groups['primary'][0]]['inventory_hostname']}}"
    bucket:
      name: makura
      type: couchbase
      ramsize: 256
      port: 11222
      replica: 1
  tasks:
  - name: Create new bucket
    couchbase-server: "command=create-bucket admin_connection={{ primary_node}}:8091 bucket_name={{ bucket.name }} bucket_type={{bucket.type}} bucket_port={{bucket.port }} bucket_ramsize={{ bucket.ramsize }} bucket_replica={{ bucket.replica }}"
