---
# File: macosx/roles/couchbase-server/ubuntu/tasks/main.yml
# Ubuntu tasks for the Couchbase Server role

# Install Couchbase Server

- name: Download Couchbase Server
  get_url: url={{ ubuntu.url }} dest=/tmp/{{ ubuntu.package }} sha256sum={{ ubuntu.sha256 }}
  tags: installation

- name: Install Couchbase Server
  command: dpkg -i /tmp/{{ ubuntu.package }}
  tags: installation

